### ISSUE TITLE
Составить стек технологий для разработки программного продукта

### ISSUE THREAD

**Issue by Timofey-arch** [Timofey-arch/DNDService#2]
Составить список инструментов для разработки программного продукта
Список должен включать в себя такие пункты как:
* Языки программирования
* Фреймворки и/или библиотеки
* Среды разработки
* Инструменты прототипирования
* Инструменты сборки
* Инструменты тестирования
* Языки разметки
* Распределённая система управления версиями

**Comment by SerLap-ctrl** [comment]
Стэк технологий для разработки программного продукта:
* Языки программирования: Typescript, Python
* Фреймворки и/или библиотеки: React.js, Next.js
* Среды разработки: VSCode, WebStorm
* Инструменты прототипирования: Figma
* Инструменты сборки: Webpack
* Инструменты тестирования: Mocha, w3c
* Языки разметки: Html, CSS
* Распределённая система управления версиями
