### ISSUE TITLE
Создать класс персонажа

### ISSUE THREAD

**Issue by SerLap-ctrl** [Timofey-arch/DNDService#8]
Создать класс, реализующий персонажа. Данный класс должен включать в себя следующие поля и методы:
* Игровой класс персонажа
* Биография
* Имя игрока
* Имя персонажа
* Раса
* Характер
* Очки опыта
* Уровень
* Основные статы:
    * Сила
    * Ловкость
    * Телосложение
    * Интеллект 
    * Мудрость
    * Харизма
* Воодушевление
* Бонус мастерства
* Спасброски, основанные на основных статах
* Навыки:
    * Акробатика
    * Дрессировка
    * Аркана
    * Атлетика
    * Обман
    * История
    * Проницательность
    * Запугивание
    * Исследование 
    * Медицина
    * Природа
    * Бдительность
    * Исполнение
    * Убеждение 
    * Религия
    * Ловкость рук
    * Скрытность
    * Выживание
* Класс брони
* Инициатива
* Скорость
* Пассивная мудрость
* Здоровье (временное и текущее)
* Инвентарь
* Особенности и черты, языки, идеалы, изъяны, кредо
 
Методы:
* Подсчет модификаторов спасбросков
* Подсчет модификаторов навыков
* Повышение уровня персонажа
* Обмен валюты в инвентаре
* Редактирование любого поля

**Comment by Timofey-arch** [comment]
Данный класс больше не понадобится
